const fs = require('fs');
const path = require('path');
const { createZip } = require('../utils/zipUtils');
const { runCommand } = require('../utils/execUtils');
const { cleanDirectory } = require('../utils/tmpUtils');

async function generateProjectZip({ artifactId, pkg, version, generatedYaml }) {
    // Base temporary directory (tmp under project root)
    const baseTmpDir = path.resolve(__dirname, '..', '..', 'tmp');
    fs.mkdirSync(baseTmpDir, { recursive: true });

    // Project folder generated by Maven
    const generatedProjectDir = path.join(baseTmpDir, artifactId);

    // ZIP output path with timestamp to avoid collisions
    const zipPath = path.resolve(baseTmpDir, `${artifactId}-${Date.now()}.zip`);

    // DEBUG: print paths
    console.log('Temporary base directory:', baseTmpDir);
    console.log('Generated project directory:', generatedProjectDir);
    console.log('ZIP file path:', zipPath);

    try {
        // Maven archetype generate command arguments
        const mvnArgs = [
            'archetype:generate',
            '-DarchetypeGroupId=com.marbl.declarative-batch',
            '-DarchetypeArtifactId=declarative-batch-archetype',
            '-DarchetypeVersion=0.0.1-SNAPSHOT',
            '-DgroupId=com.marbl',
            `-DartifactId=${artifactId}`,
            `-Dversion=${version}`,
            `-Dpackage=${pkg}`,
            '-DinteractiveMode=false'
        ];

        // Execute Maven command in the temporary directory
        await runCommand('mvn', mvnArgs, { cwd: baseTmpDir });

        // Path to src/main/resources inside the generated project
        const resourcesPath = path.join(
            generatedProjectDir,
            'src',
            'main',
            'resources'
        );
        fs.mkdirSync(resourcesPath, { recursive: true });

        // Write application.yml file
        const yamlFilePath = path.join(resourcesPath, 'application.yml');
        fs.writeFileSync(yamlFilePath, generatedYaml, 'utf8');

        // Create ZIP file from the generated project directory
        await createZip(generatedProjectDir, zipPath);

        return zipPath;

    } finally {
        // Cleanup generated project directory (keep the ZIP)
        cleanDirectory(generatedProjectDir);
    }
}

module.exports = { generateProjectZip };
